CREATE TABLE IF NOT EXISTS products (
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL,
    PRIMARY KEY (id)
)  ENGINE=MYISAM DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;